apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
spec:
  instances: {{ .Values.instances }}
  storage:
    size: {{ .Values.storage.size }}
  managed:
    roles:
    - name: {{ .Values.dbName }}
      ensure: present
      login: true
      superuser: false
      passwordSecret:
        name: {{ .Values.dbSecretName }}